language: r
cache: packages
r_check_args: --as-cran 
r_build_args: --compact-vignettes=both

r:
  - release
  - devel

os:
  - linux

matrix:
  fast_finish: true
  allow_failures:
  - r: devel

before_install:
  - export DISPLAY=:99.0
  - sudo apt-get install libcurl4-openssl-dev

services:
  - xvfb

notifications:
  email:
    on_success: change
    on_failure: change
